kafka:
  server: "localhost:9092"
  outTopicName: "TaskExecutor"
  inTopicName: "router-in-topic"
  groupId: "routerGroup"

request:
  timeout: 100,
  retries: 100

ignite:
  igniteInstanceName: properties-instance-name
  communicationSpi:
    localPort: 5555
  dataStorageConfiguration:
    defaultDataRegionConfiguration:
      initialSize: 10485760 #10MB
    dataRegionConfigurations:
      - name: my-dataregion
        initialSize: 104857600 #100MB
  cacheConfiguration:
    - name: messages
      queryEntities:
        - tableName: MESSAGES
          keyFieldName: ID
          keyType: java.lang.String
          valueType: java.lang.String
          fields:
            ID: java.lang.String
            amount: java.lang.String
            updateDate: java.util.Date